[package]
name = "pathos"
description = "Find user and system paths on your operating system or somebody else's."
version = "0.1.6"
authors = ["Brendan Molloy <brendan@bbqsrc.net>"]
edition = "2018"
license = "Apache-2.0 OR MIT"

[dependencies]
dirs = { package = "dirs-next", version = "1.0.1" }
directories = { package = "directories-next", version = "1.0.1" }
iref = "1.1.5"
thiserror = "1.0.19"
once_cell = "1.4.0"
log = "0.4.8"
libc = "0.2.71"

[dev-dependencies]
whoami = "0.8.1"

[features]
ios = []
android = []
macos = []
windows = []
linux = []
xdg = []
